export default () => ({
    equals: '$0 = $1',
    add: '$0 + $1',
    sub: '$0 - $1',
    div: '$0 : $1',
    mul: '$0 \\cdot $1',
    muli: '$0 $1',
    add_sub: '$0 \\pm $1',
    not_equals: '$0 \\neq $1',
    approx: '$0 \\approx $1',
    gt: '$0 \\gt $1',
    lt: '$0 \\lt $1',
    gte: '$0 \\ge $1',
    lte: '$0 \\le $1',
    elem_of: '$0 \\in $1',
    elem_not_of: '$0 \\notin $1',
    union: '$0 \\cup $1',
    cond_def: '$0 \\mid $1',
    cond_expr: '$0 , $1',
    diff: '$0 \\backslash $1',
    negative: '- $0',
    positive: '+ $0',
    add_sub_sign: '\\pm $0',
    approx_sign: '\\approx $0',
    differential: 'd $0',
    ln: '\\ln $c($0)$c',
    root2: '\\sqrt{$0}',
    sin: '\\sin $c($0)$c',
    cos: '\\cos $c($0)$c',
    tan: '\\tg $c($0)$c',
    cot: '\\ctg $c($0)$c',
    asin: '\\arcsin $c($0)$c',
    acos: '\\arccos $c($0)$c',
    atan: '\\arctg $c($0)$c',
    acot: '\\arcctg $c($0)$c',
    sec: '\\sec $c($0)$c',
    csc: '\\csc $c($0)$c',
    factorial: '$0!',
    percentage: '$0\\%',
    bracket: '$c($0)$c',
    abs: '$c|$0|$c',
    ooint: '$c($0; $1)$c',
    coint: '$c[$0; $1)$c',
    ocint: '$c($0; $1]$c',
    ccint: '$c[$0; $1]$c',
    indexed: '$0_{$d$1$d}',
    pow: '$c($0)$c^{$d$1$d}',
    deg: '$0^{\\circ}',
    degmin: "$0^{\\circ} $1'",
    degminsecond: "$0^{\\circ} $1' $2''",
    log: '\\log_{$d$0$d} $c($1)$c',
    root: '\\sqrt[$d$0$d]{$1}',
    frac: '\\dfrac{$0}{$1}',
    mixedfrac: '$0 \\dfrac{$1}{$2}',
    function: '$0($1)',
    function_inverse: '$0^{-1}($1)',
    derivation: '\\dfrac{d}{d $0}($1)',
    derivationprime: '$0^{\\prime}',
    derivationprime2: '$0^{\\prime\\prime}',
    nderivationprime: '$1^{($0)}',
    derivation_diff: '\\dfrac{d $0}{d $1}',
    partial_derivation: '\\dfrac{\\partial}{\\partial $0} ($1)',
    partial_derivation_diff: '\\dfrac{\\partial $0}{\\partial $1}',
    lim: '\\lim\\limits_{$0 \\to $1} $c($2)$c',
    lim_right: '\\lim\\limits_{$d$0 \\to $1^{+}$d} $c($2)$c',
    lim_left: '\\lim\\limits_{$d$0 \\to $1^{-}$d} $c($2)$c',
    integral: '\\int $0 d $1',
    definiteintegral: '\\int\\limits_{$d$0$d}^{$1} $2 d $3',
    integralrightdash: '$0 \\Bigg|^{$1}_{$d$2$d}',
    definitesigma: '\\sum\\limits_{$d$0=$1$d}^{$d$2$d} $3',
    function_operation: '($0)($1)',
    composition: '$0 \\circ $1',
    ellipsis: '\\ldots',
    choose: '\\binom{$0}{$1}'
});
